// src/lib/audio/DefaultStreams.ts
import type { DbTrack } from "./LibraryDB";

export const DEFAULT_STREAMS: Omit<DbTrack, "addedAt" | "playCount">[] = [
  {
    id: "default-stream-groovesalad",
    title: "Groove Salad (SomaFM)",
    artist: "Ambient / Downtempo",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/groovesalad-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-lush",
    title: "Lush (SomaFM)",
    artist: "Sensuous Melancholy Ambient",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/lush-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-dronezone",
    title: "Drone Zone (SomaFM)",
    artist: "Atmospheric Space Drones",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/dronezone-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-spacestation",
    title: "Space Station Soma",
    artist: "Ambient Spacemusic",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/spacestation-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-indiepop",
    title: "Indie Pop Rocks! (SomaFM)",
    artist: "Indie Rock / Alternative",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/indiepop-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-beatblender",
    title: "Beat Blender (SomaFM)",
    artist: "Midtempo Electronic / House",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/beatblender-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-secretagent",
    title: "Secret Agent (SomaFM)",
    artist: "Spy Soundtracks / Lounge",
    album: "SomaFM Streams",
    source: "remote",
    url: "https://ice1.somafm.com/secretagent-128-mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-chillhop",
    title: "Chillhop Radio",
    artist: "Lofi Hip Hop / Chill Beats",
    album: "Chillhop Music",
    source: "remote",
    url: "http://stream.chillhop.com/lofi",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-lofiradio",
    title: "Lofi Radio",
    artist: "Relaxing Lofi Studymusic",
    album: "Lofi Network",
    source: "remote",
    url: "https://play.streamafrica.net/lofiradio",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-nightride",
    title: "Nightride FM Synthwave",
    artist: "Synthwave / Outrun",
    album: "Nightride FM",
    source: "remote",
    url: "https://stream.nightride.fm/synthwave",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-synthwavehu",
    title: "Synthwave Radio Hungary",
    artist: "Retro Electro / Synthwave",
    album: "Synthwave.hu",
    source: "remote",
    url: "http://stream.synthwave.hu/live",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-bassdrive",
    title: "Bassdrive (Drum & Bass)",
    artist: "Drum & Bass / Jungle",
    album: "Bassdrive Worldwide",
    source: "remote",
    url: "http://stream.bassdrive.co:8000/stream",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-linnclassical",
    title: "Linn Classical",
    artist: "High-Fidelity Classical",
    album: "Linn Records",
    source: "remote",
    url: "http://89.16.185.174:8000/classical",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-classicfm",
    title: "Classic FM UK",
    artist: "Orchestral Classical",
    album: "Global Player",
    source: "remote",
    url: "http://icecast.mediauk.com/classicfm.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-swissclassical",
    title: "Radio Swiss Classic",
    artist: "Orchestral / Instrumental",
    album: "SRG SSR Swiss",
    source: "remote",
    url: "http://stream.srg-ssr.ch/m/rsc_de/mp3_128",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-tsfjazz",
    title: "TSF Jazz France",
    artist: "Parisian Jazz / Bebop",
    album: "TSF Radio Group",
    source: "remote",
    url: "http://tsfjazz.ice.infomaniak.ch/tsfjazz-high.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-jazzradio",
    title: "Jazz Radio France",
    artist: "Classic & Modern Jazz",
    album: "Jazz Radio Group",
    source: "remote",
    url: "http://jazzradio.ice.infomaniak.ch/jazzradio-high.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-linnjazz",
    title: "Linn Jazz",
    artist: "High-Fidelity Vocal Jazz",
    album: "Linn Records",
    source: "remote",
    url: "http://89.16.185.174:8000/jazz",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-swissgroove",
    title: "Swiss Groove",
    artist: "Soul / Funk / Acid Jazz",
    album: "Swiss Radio",
    source: "remote",
    url: "https://icecast.swissgroove.ch/128",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-kexp",
    title: "KEXP 90.3 FM Seattle",
    artist: "Eclectic Indie Rock",
    album: "KEXP Seattle",
    source: "remote",
    url: "https://kexp-mp3-128.streamguys1.com/kexp128.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-wfmu",
    title: "WFMU Freeform",
    artist: "Eclectic Freeform Rock",
    album: "WFMU East Orange",
    source: "remote",
    url: "http://stream0.wfmu.org/freeform-128k",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-rpmellow",
    title: "Radio Paradise (Mellow Mix)",
    artist: "Acoustic / Mellow Rock",
    album: "Radio Paradise",
    source: "remote",
    url: "http://stream.radioparadise.com/mellow-128",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-rpmain",
    title: "Radio Paradise (Main Mix)",
    artist: "Eclectic Rock / Alternative",
    album: "Radio Paradise",
    source: "remote",
    url: "http://stream.radioparadise.com/mp3-128",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-fip",
    title: "FIP Radio France",
    artist: "Eclectic / World Music",
    album: "Radio France",
    source: "remote",
    url: "https://stream.radiofrance.fr/fip/fip.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-nectarine",
    title: "Nectarine Demoscene",
    artist: "Tracker / Chiptune / Demo",
    album: "Demoscene Radio",
    source: "remote",
    url: "https://scenestream.net/demovibes/mp3/128/",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-kohina",
    title: "Kohina Retro Radio",
    artist: "8-bit Chiptune / 80s Games",
    album: "Kohina Network",
    source: "remote",
    url: "http://stream.kohina.com:8000/stream.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-cafedelmar",
    title: "Cafe del Mar Radio",
    artist: "Chillout / Balearic Lounge",
    album: "Cafe del Mar",
    source: "remote",
    url: "https://cafedelmar.ice.infomaniak.ch/cafedelmar-high.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-ibizaglobal",
    title: "Ibiza Global Radio",
    artist: "Deep Tech / Deep House",
    album: "Ibiza Global",
    source: "remote",
    url: "https://ibizaglobalradio.ice.infomaniak.ch/ibizaglobalradio-high.mp3",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-sleepbot",
    title: "Sleepbot Environmental",
    artist: "Dark Ambient / Space Music",
    album: "Sleepbot Broadcast",
    source: "remote",
    url: "http://listen.sleepbot.com:8080/sleepbot",
    mime: "audio/mpeg",
    isStream: true,
  },
  {
    id: "default-stream-lounge",
    title: "Lounge Radio Switzerland",
    artist: "Lounge / Ambient Jazz",
    album: "Lounge Radio Group",
    source: "remote",
    url: "http://stream.lounge-radio.com/lounge_192.mp3",
    mime: "audio/mpeg",
    isStream: true,
  }
];
